version: "3.9"

services:
  app:
    build: .
    container_name: my-bode-app
    ports:
      - "3000:3000"
    env_file:
      - .env            # 로컬 .env 값 주입
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: my-bode-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: