# .github/workflows/deploy-heroku.yml
name: Deploy to Heroku

on:
  # 1) main 브랜치에 push 될 때 실행
  push:
    branches: [main]

  # 2) (선택) CI 워크플로가 성공(completed) 시 실행
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy:
    # CI 성공 또는 직접 push 둘 중 하나만 만족해도 실행
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1) 소스 체크아웃
      - uses: actions/checkout@v3

      # 2) Heroku CLI 설치 및 로그인
      - name: Setup Heroku CLI
        uses: heroku/actions/setup-heroku@v2
        with:
          heroku_api_key:  ${{ secrets.HEROKU_API_KEY }}
          heroku_email:    ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}   # mymeaning-backend

      # 3) Git push 방식으로 배포
      - name: Deploy to Heroku
        run: |
          heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
          git push heroku HEAD:main --force