name: Deploy to Heroku

on:
  push:
    branches: [main]     # main 에 커밋될 때만 배포
  workflow_run:          # (선택) CI 통과 후에만 배포
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Heroku CLI 설치
      - uses: heroku/setup-heroku@v2
        with:
          heroku-api-key: ${{ secrets.HEROKU_API_KEY }}

      # Heroku 배포
      - name: Deploy
        run: |
          heroku git:remote -a your-heroku-app-name
          git push heroku HEAD:main --force
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}