name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Jest Tests
        env:
          NODE_ENV: test
          MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
          DB_NAME: ${{ secrets.TEST_DB_NAME }}
          SESSION_SECRET: ${{ secrets.TEST_SESSION_SECRET }}
        run: npm test -- --ci --runInBand
